services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - "5433:5432"
  redis:
    image: redis
  sidekiq:
    build: .
    environment:
    - STUDENT_PORTAL_URL=http://localhost:3000
    - RACK_ENV=development
    - RAILS_ENV=development
    command: bundle exec sidekiq
    volumes:
      - .:/home/app/webapp
    depends_on:
      - db
      - redis
  web:
    build: .
    environment:
    - STUDENT_PORTAL_URL=http://localhost:3000
    - RACK_ENV=development
    - RAILS_ENV=development
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/home/app/webapp
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
