// Generated by CoffeeScript 1.7.1
var options, stampPdf, system, webpage;

system = require("system");

webpage = require("webpage");

stampPdf = function(phantom, webpage, options) {
  var mainPage;
  mainPage = webpage.create();
  mainPage.viewportSize = {
    width: 600,
    height: 600
  };
  mainPage.paperSize = {
    format: 'A4',
    orientation: 'portrait',
    margin: '0.5cm',
    footer: {
      height: '0.3cm',
      contents: 'test'
    }
  };
  return mainPage.open(options.documentAddress, function(status) {
    if (status !== "success") {
      console.log("Unable to load the address!");
      console.log(status);
      return phantom.exit();
    } else {
      window.setTimeout((function() {
        return mainPage.evaluate(function() {
          jQuery(".form-submit-button").css("background", "#fbfbfb");
          jQuery("select").each(function(index, item) {
            var newItem, oldValue, value;
            oldValue = '';
            value = jQuery(item).find("option").filter(function(index) {
              return jQuery(jQuery(item).find("option")[index]).val() === jQuery(item).val();
            })[0];
            if (value) {
              oldValue = jQuery(value).text();
            }
            newItem = jQuery("<input type=\"text\" class=\"form-control ng-pristine ng-valid\">").val(oldValue);
            return jQuery(item).replaceWith(newItem);
          });
          jQuery("input").css("border", "1px solid gray");
          jQuery("input").css("border", "1px solid gray");
          return jQuery("input,label,span").each(function(index, item) {
            var fontSize;
            fontSize = parseInt(jQuery(item).css("font-size"));
            fontSize = (fontSize - 1) + "px";
            return jQuery(item).css("font-size", fontSize);
          });
        });
      }), 5000);
      return window.setTimeout((function() {
        mainPage.render(options.filename);
        return phantom.exit();
      }), 10000);
    }
  });
};

options = {
  documentAddress: system.args[1],
  filename: system.args[2]
};

stampPdf(phantom, webpage, options);
