// Generated by CoffeeScript 1.7.1
var options, stampPdf, system, webpage;

system = require("system");

webpage = require("webpage");

stampPdf = function(phantom, webpage, options) {
  var footerPage;
  footerPage = webpage.create();
  return footerPage.open(options.footerAddress, function(status) {
    var footer, footerBuilder, mainPage;
    footer = footerPage.content.replace("<html><head></head><body>", "").replace("</body></html>", "");
    footerBuilder = function(content, pageNum, numPages) {
      var _ref;
      return content.replace('{{page_label}}', (_ref = numPages === 1) != null ? _ref : {
        'page': 'pages'
      }).replace('{{current_page}}', pageNum + '').replace('{{total_pages}}', numPages + '');
    };
    mainPage = webpage.create();
    mainPage.viewportSize = {
      width: 600,
      height: 600
    };
    mainPage.paperSize = {
      format: 'A4',
      orientation: 'portrait',
      margin: '0.5cm',
      footer: {
        height: '0.3cm',
        contents: phantom.callback(function(pageNum, numPages) {
          return footerBuilder(footer, pageNum, numPages);
        })
      }
    };
    return mainPage.open(options.documentAddress, function(status) {
      if (status !== "success") {
        console.log("Unable to load the address!");
        console.log(status);
        return phantom.exit();
      } else {
        window.setTimeout((function() {
          return mainPage.evaluate(function() {
            jQuery(".form-submit-button").css("background", "#fbfbfb");
            jQuery("input").css("border", "1px solid gray");
            jQuery("input").css("border", "1px solid gray");
            jQuery("[bgcolor]").each(function(index, item) {
              item = jQuery(item);
              return item.css("background-color", item.attr('bgcolor') + " !important");
            });
            return jQuery("input,label,span").each(function(index, item) {
              var fontSize;
              fontSize = parseInt(jQuery(item).css("font-size"));
              fontSize = (fontSize - 1) + "px";
              return jQuery(item).css("font-size", fontSize);
            });
          });
        }), 5000);
        return window.setTimeout((function() {
          mainPage.render(options.filename);
          return phantom.exit();
        }), 10000);
      }
    });
  });
};

options = {
  documentAddress: system.args[1],
  footerAddress: system.args[2],
  filename: system.args[3]
};

stampPdf(phantom, webpage, options);
