production:
  adapter: postgresql
  encoding: unicode
  database: new_charter
  host: diamond-db-production1.cj8aalmd5rsa.us-east-1.rds.amazonaws.com
  pool: 25
  username: postgres
  password: 1d9a10ec-dffd-48b1-a493-6037e9aa14d3
  min_messages: warning
